import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { SalonNavbar } from '@/components/SalonNavbar';
import { SalonFooter } from '@/components/SalonFooter';
import { LocalDB } from '@/services/LocalDatabase';
import { ArrowLeft, Calendar, User } from 'lucide-react';

const BlogPostPage = () => {
  const { slug } = useParams();
  const [blog, setBlog] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchBlog = async () => {
      if (!slug) return;
      setLoading(true);
      const { data } = await LocalDB.getBlogBySlug(slug);
      setBlog(data);
      setLoading(false);
    };
    fetchBlog();
  }, [slug]);

  useEffect(() => {
    if (blog) {
      document.title = blog.meta_title || `${blog.title} | Alanís Salon Blog`;
    }
  }, [blog]);

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col">
        <SalonNavbar />
        <div className="flex-1 flex justify-center items-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-accent"></div>
        </div>
        <SalonFooter />
      </div>
    );
  }

  if (!blog) {
    return (
      <div className="min-h-screen flex flex-col">
        <SalonNavbar />
        <div className="flex-1 flex flex-col justify-center items-center text-center p-6">
          <h1 className="font-display text-4xl mb-4">Article not found</h1>
          <p className="font-body text-muted-foreground mb-8">The article you are looking for does not exist or has been moved.</p>
          <Link to="/blog" className="inline-flex items-center gap-2 bg-accent text-white px-6 py-3 rounded-full font-bold hover:bg-accent/90 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to Blog
          </Link>
        </div>
        <SalonFooter />
      </div>
    );
  }

  // Format date
  const publishDate = blog.created_at ? new Date(blog.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }) : '';

  return (
    <div className="min-h-screen bg-background">
      <SalonNavbar />

      <article className="pt-24 md:pt-32 pb-24">
        {/* Header Section */}
        <div className="container mx-auto px-6 max-w-4xl text-center mb-12">
          {/* Floating/visible back button */}
          <div className="flex justify-center md:justify-start mb-8 md:-ml-12 lg:-ml-24">
            <Link to="/blog" className="inline-flex items-center gap-2 bg-accent text-white shadow-md hover:bg-accent/90 transition-all px-6 py-3 rounded-full font-body text-xs uppercase tracking-widest font-bold">
              <ArrowLeft className="w-4 h-4" /> Back to Blog
            </Link>
          </div>
          
          <h1 className="font-display text-4xl md:text-6xl font-medium leading-[1.1] mb-6">
            {blog.title}
          </h1>

          <div className="flex flex-wrap items-center justify-center gap-6 text-sm text-muted-foreground font-body uppercase tracking-widest">
            <div className="flex items-center gap-2">
              <User className="w-4 h-4" />
              <span>Alanís Salon</span>
            </div>
            {publishDate && (
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4" />
                <span>{publishDate}</span>
              </div>
            )}
          </div>
        </div>

        {/* Featured Image */}
        {blog.image && (
          <div className="container mx-auto px-6 max-w-5xl mb-16">
            <div className="aspect-[21/9] md:aspect-[2.5/1] rounded-[2.5rem] overflow-hidden shadow-2xl">
              <img 
                src={blog.image} 
                alt={blog.title}
                className="w-full h-full object-cover"
              />
            </div>
          </div>
        )}

        {/* Content Section */}
        <div className="container mx-auto px-6 max-w-3xl">
          <div className="prose prose-lg md:prose-xl prose-stone max-w-none 
                          prose-headings:font-display prose-headings:font-medium 
                          prose-p:font-body prose-p:leading-relaxed prose-p:text-muted-foreground
                          prose-a:text-accent prose-a:no-underline hover:prose-a:underline
                          prose-img:rounded-3xl prose-img:shadow-xl">
            {/* The blog content generated by the admin is usually HTML */}
            <div dangerouslySetInnerHTML={{ __html: blog.content }} />
          </div>
        </div>
      </article>

      <SalonFooter />
    </div>
  );
};

export default BlogPostPage;
